### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Horkyze** [Horkyze/software-router.dotNet#2]
Router fails to search static route when its defined only by interface

- [x] - Interface stats (in/out - number of packets)
- [x] - Implement sending ICMP request (ping)
- [x] - Send RIP request - when rip turns on
- [x] -  RIP timers
- [ ] - Check loks (maybe use thread safe collections?)
